[package]
name = "viewer"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["wasm-web"]
wasm-web = [
    "eozin/wasm-web",
    "dep:web-sys",
    "dep:wasm-bindgen-futures",
    "dep:wasm-bindgen",
    "dep:js-sys",
    "dep:serde",
    "dep:tsify",
]

[dependencies]
eozin = { path = "../", default-features = false }
wasm-bindgen = { workspace=true, optional=true }
futures = { workspace=true }
wasm-bindgen-futures = { workspace=true, optional = true }
serde = { optional = true, workspace = true, features = ["derive"] }
js-sys = { workspace = true, optional = true }
tsify = { workspace=true, optional=true }

[dependencies.web-sys]
workspace=true
optional = true
features=[
  "HtmlCanvasElement",
  "CanvasRenderingContext2d",
  "ImageBitmap",
  "AddEventListenerOptions",
  "EventTarget",
  "MouseEvent",
  "WheelEvent",
  "TouchEvent",
  "TouchList",
  "Touch",
  "Element",
  "DomRect",
  "Blob",
  "BlobPropertyBag",
  "console",
  "ImageData",
  "File",
  "Worker",
  "WorkerGlobalScope"
]
