name: Deploy Multi-Platform Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Public Folder
        run: mkdir -p public/docs/python

      - name: Build Python Docs (MkDocs)
        run: |
          pip install mkdocs-material mkdocstrings[python]
          mkdocs build -f py-eozin/python/mkdocs.yml
          cp -r py-eozin/python/site/* public/docs/python/

      - name: Upload JS part
        uses: actions/upload-artifact@v4
        with:
          name: docs-py
          path: public

  build-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Public Folder
        run: mkdir -p public/docs/js

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install build script dependencies
        run: |
          cd js-eozin
          npm ci

      - name: Build Web Package(Dev mode)
        run: |
          cd js-eozin
          node scripts/build.js @eozin/eozin-web-dev

      - name: Build Node Package(Dev mode)
        run: |
          cd js-eozin
          node scripts/build.js @eozin/eozin-node-dev

      - name: Build JS Docs (TypeDoc)
        run: |
          cd js-eozin
          npm run docs
          cp -r docs/api/* ../public/docs/js/

      - name: Upload JS part
        uses: actions/upload-artifact@v4
        with:
          name: docs-js
          path: public

  build-lp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Public Folder
        run: mkdir -p public/

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install build script dependencies
        run: |
          cd web
          npm ci
          cp -r dist/* ../public/

      - name: Build LP Web Page with Vite
        run: |
          cd web
          npm run build

      - name: Upload LP part
        uses: actions/upload-artifact@v4
        with:
          name: docs-lp
          path: public

  deploy:
    needs: [build-python, build-js, build-lp]

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Download all parts
        uses: actions/download-artifact@v4
        with:
          pattern: docs-*
          merge-multiple: true
          path: final_public

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: final_public
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
